"""work requirement, crew requirement, worker safety qualification

Revision ID: 8dab9686c4fa
Revises: 9b350830f0b7
Create Date: 2026-09-18 06:21:02.967665

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dab9686c4fa'
down_revision: Union[str, None] = '9b350830f0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contractor_user_id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('requested_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_requirements_contractor_user_id'), 'work_requirements', ['contractor_user_id'], unique=False)
    op.create_table('crew_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('safety_qualification_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_requirement_id'], ['work_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_requirements_task_id'), 'crew_requirements', ['task_id'], unique=False)
    op.create_index(op.f('ix_crew_requirements_work_requirement_id'), 'crew_requirements', ['work_requirement_id'], unique=False)
    op.create_table('worker_safety_qualifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'task_id', name='uq_worker_safety_qualification_worker_task')
    )
    op.create_index(op.f('ix_worker_safety_qualifications_task_id'), 'worker_safety_qualifications', ['task_id'], unique=False)
    # server_default=true so this is safe against a DB that already has
    # `workers` rows (a plain NOT NULL ADD COLUMN with no default fails on
    # SQLite, and would silently leave existing rows unavailable on
    # Postgres) — not autogenerated as such; adjusted by hand to match the
    # ORM-level default=True on WorkerModel.is_available.
    op.add_column(
        'workers',
        sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers') as batch_op:
        batch_op.drop_column('is_available')
    op.drop_index(op.f('ix_worker_safety_qualifications_task_id'), table_name='worker_safety_qualifications')
    op.drop_table('worker_safety_qualifications')
    op.drop_index(op.f('ix_crew_requirements_work_requirement_id'), table_name='crew_requirements')
    op.drop_index(op.f('ix_crew_requirements_task_id'), table_name='crew_requirements')
    op.drop_table('crew_requirements')
    op.drop_index(op.f('ix_work_requirements_contractor_user_id'), table_name='work_requirements')
    op.drop_table('work_requirements')
    # ### end Alembic commands ###
