"""dispatch position, dispatch offer

Revision ID: 9dc6a984897e
Revises: 8dab9686c4fa
Create Date: 2026-09-25 14:10:57.616249

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc6a984897e'
down_revision: Union[str, None] = '8dab9686c4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('crew_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'COMMITTED' AND worker_id IS NOT NULL) OR (status != 'COMMITTED' AND worker_id IS NULL)", name='ck_dispatch_position_committed_worker'),
    sa.ForeignKeyConstraint(['crew_requirement_id'], ['crew_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_requirement_id'], ['work_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_requirement_id', 'position_index', name='uq_dispatch_position_line_index')
    )
    op.create_index('ix_dispatch_position_work_requirement', 'dispatch_positions', ['work_requirement_id'], unique=False)
    op.create_index('ix_dispatch_position_worker_status', 'dispatch_positions', ['worker_id', 'status'], unique=False)
    op.create_index(op.f('ix_dispatch_positions_crew_requirement_id'), 'dispatch_positions', ['crew_requirement_id'], unique=False)
    op.create_table('dispatch_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['dispatch_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispatch_offer_position_status', 'dispatch_offers', ['position_id', 'status'], unique=False)
    op.create_index('ix_dispatch_offer_status_expires', 'dispatch_offers', ['status', 'expires_at'], unique=False)
    op.create_index('ix_dispatch_offer_worker_status', 'dispatch_offers', ['worker_id', 'status'], unique=False)
    op.create_index('uq_dispatch_offer_position_worker_pending', 'dispatch_offers', ['position_id', 'worker_id'], unique=True, sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_dispatch_offer_position_worker_pending', table_name='dispatch_offers', sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_dispatch_offer_worker_status', table_name='dispatch_offers')
    op.drop_index('ix_dispatch_offer_status_expires', table_name='dispatch_offers')
    op.drop_index('ix_dispatch_offer_position_status', table_name='dispatch_offers')
    op.drop_table('dispatch_offers')
    op.drop_index(op.f('ix_dispatch_positions_crew_requirement_id'), table_name='dispatch_positions')
    op.drop_index('ix_dispatch_position_worker_status', table_name='dispatch_positions')
    op.drop_index('ix_dispatch_position_work_requirement', table_name='dispatch_positions')
    op.drop_table('dispatch_positions')
    # ### end Alembic commands ###
